name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    paths: [ 'kohomology-browser/**', 'kohomology-cli/**', '.github/workflows/gradle.yml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'kohomology-browser/**', 'kohomology-cli/**', '.github/workflows/gradle.yml' ]

jobs:
  build-browser:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [browser, cli]

    defaults:
      run:
        working-directory: kohomology-${{ matrix.project }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ matrix.project }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-${{ matrix.project }}-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile with Gradle
        run: ./gradlew compileKotlin
      # - name: Run
      #   run: ./gradlew run # This does not finish for kohomology-browser
