name: Publish github pages

on:
  push:
    branches: [ main ]
    paths: [ 'kohomology-react/**', '.github/workflows/pages.yml' ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kohomology-react
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-react-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-react-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemble # build だと ktlintCheck も実行してしまう
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: kohomology-react/build/distributions/
